services:
  workshop-env:
    image: python:3.11-slim
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    working_dir: /workspaces/${localWorkspaceFolderBasename}
    user: "1000:1000"
    environment:
      - PYTHONPATH=/workspaces/${localWorkspaceFolderBasename}